@baseUrl = http://localhost:8000

### Start session (reuse or create)
POST {{baseUrl}}/sessions/start
Accept: application/json

### Login to session (replace TAG123)
POST {{baseUrl}}/sessions/login?game_tag=TAG123
Accept: application/json


### End session (replace 10.0.0.1)
POST {{baseUrl}}/sessions/end?droplet_ip=10.0.0.1
Accept: application/json

### Heartbeat
POST {{baseUrl}}/server/heartbeat
Content-Type: application/json
Accept: application/json

{
  "droplet_ip": "10.0.0.1",
  "connected_clients": 1
}