@localTestOrchestratorURL = "http://127.0.0.1:8000"

GET {{localTestOrchestratorURL}}/

###  Send heartbeat
POST {{localTestOrchestratorURL}}/server/heartbeat?droplet_ip=10.0.0.1

###  Stop a server
POST {{localTestOrchestratorURL}}/server/end?droplet_ip=10.0.0.1

### Start a server
POST {{localTestOrchestratorURL}}/sessions/start

